# Generated by Django 4.1.6 on 2023-02-10 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="naslovObjave",
        ),
        migrations.RemoveField(
            model_name="post",
            name="objavaContent",
        ),
        migrations.AddField(
            model_name="post",
            name="datePublished",
            field=models.DateField(default=datetime.date(2023, 2, 10)),
        ),
        migrations.AddField(
            model_name="post",
            name="featuredImage",
            field=models.ImageField(default="Null", upload_to="media/"),
        ),
        migrations.AddField(
            model_name="post",
            name="postContent",
            field=models.TextField(default="Null"),
        ),
        migrations.AddField(
            model_name="post",
            name="postName",
            field=models.CharField(default="Null", max_length=120),
        ),
    ]
