# Generated by Django 4.1.6 on 2023-02-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0002_remove_post_naslovobjave_remove_post_objavacontent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featuredImage",
            field=models.ImageField(default="", upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="postContent",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="postName",
            field=models.CharField(default="", max_length=120),
        ),
    ]
