# Generated by Django 4.1.7 on 2023-04-01 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0003_alter_post_featuredimage_alter_post_postcontent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="datePublished",
            field=models.DateField(default=datetime.date(2023, 4, 1)),
        ),
    ]
